const americaDelSur = [
  "Beni",
  "Chuquisaca",
  "Cochabamba",
  "La Paz",
  "Oruro",
  "Pando",
  "Potosí",
  "Santa Cruz",
  "Tarija",

  "Acre",
  "Alagoas",
  "Amapá",
  "Amazonas",
  "Bahia",
  "Ceará",
  "Distrito Federal",
  "Espírito Santo",
  "Goiás",
  "Maranhão",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Pará",
  "Paraíba",
  "Paraná",
  "Pernambuco",
  "Piauí",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondônia",
  "Roraima",
  "Santa Catarina",
  "São Paulo",
  "Sergipe",
  "Tocantins",

  "Arica y Parinacota",
  "Tarapacá",
  "Antofagasta",
  "Atacama",
  "Coquimbo",
  "Valparaíso",
  "Región Metropolitana de Santiago",
  "O'Higgins",
  "Maule",
  "Ñuble",
  "Biobío",
  "Araucanía",
  "Los Ríos",
  "Los Lagos",
  "Aysén",
  "Magallanes y de la Antártica Chilena",

  "Amazonas",
  "Antioquia",
  "Arauca",
  "Atlántico",
  "Bolívar",
  "Boyacá",
  "Caldas",
  "Caquetá",
  "Casanare",
  "Cauca",
  "Cesar",
  "Chocó",
  "Córdoba",
  "Cundinamarca",
  "Guainía",
  "Guaviare",
  "Huila",
  "La Guajira",
  "Magdalena",
  "Meta",
  "Nariño",
  "Norte de Santander",
  "Putumayo",
  "Quindío",
  "Risaralda",
  "San Andrés y Providencia",
  "Santander",
  "Sucre",
  "Tolima",
  "Valle del Cauca",
  "Vaupés",
  "Vichada",
  "Bogotá D.C.",

  "Azuay",
  "Bolívar",
  "Cañar",
  "Carchi",
  "Chimborazo",
  "Cotopaxi",
  "El Oro",
  "Esmeraldas",
  "Galápagos",
  "Guayas",
  "Imbabura",
  "Loja",
  "Los Ríos",
  "Manabí",
  "Morona Santiago",
  "Napo",
  "Orellana",
  "Pastaza",
  "Pichincha",
  "Santa Elena",
  "Santo Domingo de los Tsáchilas",
  "Sucumbíos",
  "Tungurahua",
  "Zamora Chinchipe",

  "Barima-Waini",
  "Cuyuni-Mazaruni",
  "Demerara-Mahaica",
  "East Berbice-Corentyne",
  "Essequibo Islands-West Demerara",
  "Mahaica-Berbice",
  "Pomeroon-Supenaam",
  "Potaro-Siparuni",
  "Upper Demerara-Berbice",
  "Upper Takutu-Upper Essequibo",

  "Alto Paraguay",
  "Alto Paraná",
  "Amambay",
  "Asunción",
  "Boquerón",
  "Caaguazú",
  "Caazapá",
  "Canindeyú",
  "Central",
  "Concepción",
  "Cordillera",
  "Guairá",
  "Itapúa",
  "Misiones",
  "Ñeembucú",
  "Paraguarí",
  "Presidente Hayes",
  "San Pedro",

  "Amazonas",
  "Áncash",
  "Apurímac",
  "Arequipa",
  "Ayacucho",
  "Cajamarca",
  "Callao",
  "Cusco",
  "Huancavelica",
  "Huánuco",
  "Ica",
  "Junín",
  "La Libertad",
  "Lambayeque",
  "Lima",
  "Loreto",
  "Madre de Dios",
  "Moquegua",
  "Pasco",
  "Piura",
  "Puno",
  "San Martín",
  "Tacna",
  "Tumbes",
  "Ucayali",

  "Brokopondo",
  "Commewijne",
  "Coronie",
  "Marowijne",
  "Nickerie",
  "Para",
  "Paramaribo",
  "Saramacca",
  "Sipaliwini",
  "Wanica",

  "Artigas",
  "Canelones",
  "Cerro Largo",
  "Colonia",
  "Durazno",
  "Flores",
  "Florida",
  "Lavalleja",
  "Maldonado",
  "Montevideo",
  "Paysandú",
  "Río Negro",
  "Rivera",
  "Rocha",
  "Salto",
  "San José",
  "Soriano",
  "Tacuarembó",
  "Treinta y Tres",

  "Amazonas",
  "Anzoátegui",
  "Apure",
  "Aragua",
  "Barinas",
  "Bolívar",
  "Carabobo",
  "Cojedes",
  "Delta Amacuro",
  "Distrito Capital",
  "Falcón",
  "Guárico",
  "La Guaira",
  "Lara",
  "Mérida",
  "Miranda",
  "Monagas",
  "Nueva Esparta",
  "Portuguesa",
  "Sucre",
  "Táchira",
  "Trujillo",
  "Yaracuy",
  "Zulia",
  "Dependencias Federales",
];
const americaCentral = [
  // Belice
  "Belice",
  "Cayo",
  "Corozal",
  "Orange Walk",
  "Stann Creek",
  "Toledo",

  // Costa Rica
  "Alajuela",
  "Cartago",
  "Guanacaste",
  "Heredia",
  "Limón",
  "Puntarenas",
  "San José",

  // El Salvador
  "Ahuachapán",
  "Cabañas",
  "Chalatenango",
  "Cuscatlán",
  "La Libertad",
  "La Paz",
  "La Unión",
  "Morazán",
  "San Miguel",
  "San Salvador",
  "Santa Ana",
  "San Vicente",
  "Sonsonate",
  "Usulután",

  // Guatemala
  "Alta Verapaz",
  "Baja Verapaz",
  "Chimaltenango",
  "Chiquimula",
  "El Progreso",
  "Escuintla",
  "Guatemala",
  "Huehuetenango",
  "Izabal",
  "Jalapa",
  "Jutiapa",
  "Petén",
  "Quetzaltenango",
  "Quiché",
  "Retalhuleu",
  "Sacatepéquez",
  "San Marcos",
  "Santa Rosa",
  "Sololá",
  "Suchitepéquez",
  "Totonicapán",
  "Zacapa",

  // Honduras
  "Atlántida",
  "Choluteca",
  "Colón",
  "Comayagua",
  "Copán",
  "Cortés",
  "El Paraíso",
  "Francisco Morazán",
  "Gracias a Dios",
  "Intibucá",
  "Islas de la Bahía",
  "La Paz",
  "Lempira",
  "Ocotepeque",
  "Olancho",
  "Santa Bárbara",
  "Valle",
  "Yoro",

  // Nicaragua
  "Boaco",
  "Carazo",
  "Chinandega",
  "Chontales",
  "Estelí",
  "Granada",
  "Jinotega",
  "León",
  "Madriz",
  "Managua",
  "Masaya",
  "Matagalpa",
  "Nueva Segovia",
  "Rivas",
  "Río San Juan",
  "Región Autónoma de la Costa Caribe Norte",
  "Región Autónoma de la Costa Caribe Sur",

  // Panamá
  "Bocas del Toro",
  "Chiriquí",
  "Coclé",
  "Colón",
  "Darién",
  "Herrera",
  "Los Santos",
  "Panamá",
  "Veraguas",
  "Guna Yala",
  "Ngäbe-Buglé",
  "Emberá-Wounaan",
];
const americaDelNorte = [
  // Canadá (Provincias y Territorios)
  "Alberta",
  "Columbia Británica",
  "Isla del Príncipe Eduardo",
  "Manitoba",
  "Nuevo Brunswick",
  "Terranova y Labrador",
  "Nueva Escocia",
  "Ontario",
  "Quebec",
  "Saskatchewan",
  "Territorios del Noroeste",
  "Nunavut",
  "Yukón",

  // Estados Unidos (Estados y Distrito Federal)
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Carolina del Norte",
  "Carolina del Sur",
  "Colorado",
  "Connecticut",
  "Dakota del Norte",
  "Dakota del Sur",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawái",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Luisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Míchigan",
  "Minnesota",
  "Misisipi",
  "Misuri",
  "Montana",
  "Nebraska",
  "Nevada",
  "Nueva Hampshire",
  "Nueva Jersey",
  "Nuevo México",
  "Nueva York",
  "Ohio",
  "Oklahoma",
  "Oregón",
  "Pensilvania",
  "Rhode Island",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Virginia Occidental",
  "Washington",
  "Wisconsin",
  "Wyoming",
  "Distrito de Columbia",

  // México (Estados y Ciudad de México)
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Coahuila",
  "Colima",
  "Durango",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "México",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
];
const europa = [
  // Albania
  "Berat",
  "Dibër",
  "Durrës",
  "Elbasan",
  "Fier",
  "Gjirokastër",
  "Korçë",
  "Kukës",
  "Lezhë",
  "Shkodër",
  "Tirana",
  "Vlorë",

  // Alemania (Estados Federados)
  "Baden-Wurtemberg",
  "Baviera",
  "Berlín",
  "Brandeburgo",
  "Bremen",
  "Hamburgo",
  "Hesse",
  "Mecklemburgo-Pomerania Occidental",
  "Baja Sajonia",
  "Renania del Norte-Westfalia",
  "Renania-Palatinado",
  "Sarre",
  "Sajonia",
  "Sajonia-Anhalt",
  "Schleswig-Holstein",
  "Turingia",

  // Andorra (Parroquias)
  "Andorra la Vella",
  "Canillo",
  "Encamp",
  "Escaldes-Engordany",
  "La Massana",
  "Ordino",
  "Sant Julià de Lòria",

  // Armenia (Provincias)
  "Aragatsotn",
  "Ararat",
  "Armavir",
  "Gegharkunik",
  "Kotayk",
  "Lori",
  "Shirak",
  "Syunik",
  "Tavush",
  "Vayots Dzor",
  "Yerevan",
  "Artsaj",

  // Austria (Estados Federados)
  "Burgenland",
  "Carintia",
  "Baja Austria",
  "Alta Austria",
  "Salzburgo",
  "Estiria",
  "Tirol",
  "Vorarlberg",
  "Viena",

  // Azerbaiyán (Regiones)
  "Abşeron",
  "Ağcabədi",
  "Ağdam",
  "Ağdaş",
  "Ağstafa",
  "Ağsu",
  "Astara",
  "Babək",
  "Bakı",
  "Balakən",
  "Bərdə",
  "Beyləqan",
  "Biləsuvar",
  "Cəbrayıl",
  "Cəlilabad",
  "Culfa",
  "Daşkəsən",
  "Füzuli",
  "Gədəbəy",
  "Gəncə",
  "Goranboy",
  "Göyçay",
  "Göygöl",
  "Hacıqabul",
  "Horadiz",
  "İmişli",
  "İsmayıllı",
  "Kəlbəcər",
  "Kəngərli",
  "Kürdəmir",
  "Laçın",
  "Lerik",
  "Lənkəran",
  "Masallı",
  "Mingəçevir",
  "Naftalan",
  "Neftçala",
  "Oğuz",
  "Ordubad",
  "Qəbələ",
  "Qax",
  "Qazax",
  "Qobustan",
  "Quba",
  "Qubadlı",
  "Qusar",
  "Saatlı",
  "Sabirabad",
  "Salyan",
  "Samux",
  "Şabran",
  "Şahbuz",
  "Şəki",
  "Şamaxı",
  "Şəmkir",
  "Şərur",
  "Şirvan",
  "Şuşa",
  "Siyəzən",
  "Sumqayıt",
  "Tərtər",
  "Tovuz",
  "Ucar",
  "Xaçmaz",
  "Xankəndi",
  "Xızı",
  "Xocalı",
  "Xocavənd",
  "Yardımlı",
  "Yevlax",
  "Zaqatala",
  "Zəngilan",
  "Zərdab",

  // Bélgica (Regiones y Comunidades)
  "Bruselas-Capital",
  "Flandes",
  "Valonia",

  // Bielorrusia (Provincias)
  "Brest",
  "Gómel",
  "Grodno",
  "Maguilov",
  "Minsk",
  "Vítebsk",

  // Bosnia y Herzegovina (Entidades y Cantones)
  "Federación de Bosnia y Herzegovina",
  "República Srpska",
  "Distrito de Brčko",

  // Bulgaria (Provincias)
  "Blagoevgrad",
  "Burgas",
  "Dobrich",
  "Gabrovo",
  "Haskovo",
  "Jambol",
  "Kardzhali",
  "Kyustendil",
  "Lovech",
  "Montana",
  "Pazardzhik",
  "Pernik",
  "Pleven",
  "Plovdiv",
  "Razgrad",
  "Ruse",
  "Shumen",
  "Silistra",
  "Sliven",
  "Smolyan",
  "Sofía",
  "Stara Zagora",
  "Targovishte",
  "Varna",
  "Veliko Tarnovo",
  "Vidin",
  "Vratsa",

  // Chipre (Distritos)
  "Famagusta",
  "Kyrenia",
  "Larnaca",
  "Limassol",
  "Nicosia",
  "Paphos",

  // Croacia (Condados)
  "Bjelovar-Bilogora",
  "Brod-Posavina",
  "Dubrovnik-Neretva",
  "Istria",
  "Karlovac",
  "Koprivnica-Križevci",
  "Krapina-Zagorje",
  "Lika-Senj",
  "Međimurje",
  "Osijek-Baranja",
  "Požega-Eslavonia",
  "Primorje-Gorski Kotar",
  "Sisak-Moslavina",
  "Split-Dalmacia",
  "Šibenik-Knin",
  "Varaždin",
  "Virovitica-Podravina",
  "Vukovar-Sirmia",
  "Zadar",
  "Zagreb",
  "Zagreb (Ciudad)",

  // Dinamarca (Regiones)
  "Hovedstaden",
  "Midtjylland",
  "Nordjylland",
  "Sjælland",
  "Syddanmark",

  // Eslovaquia (Regiones)
  "Bratislava",
  "Trnava",
  "Trenčín",
  "Nitra",
  "Žilina",
  "Banská Bystrica",
  "Prešov",
  "Košice",

  // Eslovenia (Regiones Estadísticas)
  "Gorenjska",
  "Goriška",
  "Jugovzhodna Slovenija",
  "Koroška",
  "Obalno-kraška",
  "Osrednjeslovenska",
  "Podravska",
  "Pomurska",
  "Primorsko-notranjska",
  "Savinjska",
  "Zasavska",
  "Posavska",

  // España (Comunidades Autónomas y Ciudades Autónomas)
  "Andalucía",
  "Aragón",
  "Asturias",
  "Baleares",
  "Canarias",
  "Cantabria",
  "Castilla-La Mancha",
  "Castilla y León",
  "Cataluña",
  "Ceuta",
  "Extremadura",
  "Galicia",
  "La Rioja",
  "Madrid",
  "Melilla",
  "Murcia",
  "Navarra",
  "País Vasco",
  "Valencia",

  // Estonia (Condados)
  "Harju",
  "Hiiu",
  "Ida-Viru",
  "Jõgeva",
  "Järva",
  "Lääne",
  "Lääne-Viru",
  "Põlva",
  "Pärnu",
  "Rapla",
  "Saare",
  "Tartu",
  "Valga",
  "Viljandi",
  "Võru",

  // Finlandia (Regiones)
  "Laponia",
  "Pohjois-Pohjanmaa",
  "Kainuu",
  "Pohjois-Savo",
  "Pohjois-Karjala",
  "Keski-Suomi",
  "Etelä-Savo",
  "Etelä-Karjala",
  "Pohjanmaa",
  "Satakunta",
  "Pirkanmaa",
  "Varsinais-Suomi",
  "Uusimaa",
  "Kymenlaakso",
  "Päijät-Häme",
  "Kanta-Häme",
  "Åland",

  // Francia (Regiones)
  "Auvernia-Ródano-Alpes",
  "Borgoña-Franco Condado",
  "Bretaña",
  "Centro-Valle de Loira",
  "Córcega",
  "Gran Este",
  "Hauts-de-France",
  "Isla de Francia",
  "Normandía",
  "Nueva Aquitania",
  "Occitania",
  "Países del Loira",
  "Provenza-Alpes-Costa Azul",
  "Guayana Francesa",
  "Guadalupe",
  "Martinica",
  "Reunión",
  "Mayotte",

  // Georgia (Regiones)
  "Abkhazia",
  "Adjara",
  "Guria",
  "Imereti",
  "Kakheti",
  "Kvemo Kartli",
  "Mtskheta-Mtianeti",
  "Racha-Lechkhumi y Kvemo Svaneti",
  "Samtsje-Yavajeti",
  "Samegrelo-Zemo Svaneti",
  "Shida Kartli",
  "Tbilisi",

  // Grecia (Regiones)
  "Ática",
  "Ática Oriental",
  "Ática Occidental",
  "El Pireo",
  "Ática Central",
  "Epiro",
  "Grecia Central",
  "Grecia Occidental",
  "Islas Jónicas",
  "Macedonia Central",
  "Macedonia Occidental",
  "Macedonia Oriental y Tracia",
  "Peloponeso",
  "Tesalia",
  "Creta",
  "Egeo Meridional",
  "Egeo Septentrional",
  "Monte Athos",

  // Hungría (Condados)
  "Bács-Kiskun",
  "Baranya",
  "Békés",
  "Borsod-Abaúj-Zemplén",
  "Csongrád-Csanád",
  "Fejér",
  "Győr-Moson-Sopron",
  "Hajdú-Bihar",
  "Heves",
  "Jász-Nagykun-Szolnok",
  "Komárom-Esztergom",
  "Nógrád",
  "Pest",
  "Somogy",
  "Szabolcs-Szatmár-Bereg",
  "Tolna",
  "Vas",
  "Veszprém",
  "Zala",
  "Budapest",

  // Irlanda (Condados)
  "Carlow",
  "Cavan",
  "Clare",
  "Cork",
  "Donegal",
  "Dublín",
  "Galway",
  "Kerry",
  "Kildare",
  "Kilkenny",
  "Laois",
  "Leitrim",
  "Limerick",
  "Longford",
  "Louth",
  "Mayo",
  "Meath",
  "Monaghan",
  "Offaly",
  "Roscommon",
  "Sligo",
  "Tipperary",
  "Waterford",
  "Westmeath",
  "Wexford",
  "Wicklow",

  // Islandia (Regiones)
  "Austurland",
  "Höfuðborgarsvæðið",
  "Norðurland eystra",
  "Norðurland vestra",
  "Suðurland",
  "Suðurnes",
  "Vestfirðir",
  "Vesturland",

  // Italia (Regiones)
  "Abruzos",
  "Basilicata",
  "Calabria",
  "Campania",
  "Emilia-Romaña",
  "Friuli-Venecia Julia",
  "Lacio",
  "Liguria",
  "Lombardía",
  "Marcas",
  "Molise",
  "Piamonte",
  "Apulia",
  "Cerdeña",
  "Sicilia",
  "Toscana",
  "Trentino-Alto Adigio",
  "Umbría",
  "Valle de Aosta",
  "Véneto",

  // Letonia (Regiones)
  "Kurzeme",
  "Latgale",
  "Riga",
  "Vidzeme",
  "Zemgale",

  // Lituania (Condados)
  "Alytaus",
  "Kauno",
  "Klaipėdos",
  "Marijampolės",
  "Panevėžio",
  "Šiaulių",
  "Tauragės",
  "Telšių",
  "Utenos",
  "Vilniaus",

  // Luxemburgo (Distritos)
  "Diekirch",
  "Grevenmacher",
  "Luxemburgo",

  // Malta (Regiones)
  "Central",
  "Gozo y Comino",
  "Norte",
  "Norte de Malta",
  "Sur",
  "Sur Este",

  // Moldavia (Distritos y Unidades Territoriales)
  "Anenii Noi",
  "Bălți",
  "Basarabeasca",
  "Bender",
  "Briceni",
  "Cahul",
  "Cantemir",
  "Călărași",
  "Căușeni",
  "Chișinău",
  "Cimișlia",
  "Criuleni",
  "Dondușeni",
  "Drochia",
  "Dubăsari",
  "Edineț",
  "Fălești",
  "Florești",
  "Glodeni",
  "Hîncești",
  "Ialoveni",
  "Leova",
  "Nisporeni",
  "Ocnița",
  "Orhei",
  "Rezina",
  "Rîșcani",
  "Sîngerei",
  "Soroca",
  "Șoldănești",
  "Ștefan Vodă",
  "Strășeni",
  "Taraclia",
  "Telenești",
  "Ungheni",
  "Găgăuzia",
  "Transnistria",

  // Mónaco
  "La Condamine",
  "Monaco-Ville",
  "Monte Carlo",
  "Fontvieille",

  // Montenegro (Municipios)
  "Andrijevica",
  "Bar",
  "Berane",
  "Bijelo Polje",
  "Budva",
  "Cetinje",
  "Danilovgrad",
  "Gusinje",
  "Herceg Novi",
  "Kolašin",
  "Kotor",
  "Mojkovac",
  "Nikšić",
  "Petnjica",
  "Plav",
  "Pljevlja",
  "Plužine",
  "Podgorica",
  "Rožaje",
  "Šavnik",
  "Tivat",
  "Tuzi",
  "Ulcinj",
  "Žabljak",

  // Noruega (Condados)
  "Agder",
  "Innlandet",
  "Møre og Romsdal",
  "Nordland",
  "Oslo",
  "Rogaland",
  "Troms og Finnmark",
  "Trøndelag",
  "Vestfold og Telemark",
  "Vestland",
  "Viken",

  // Países Bajos (Provincias)
  "Brabante Septentrional",
  "Drente",
  "Flevoland",
  "Frisia",
  "Güeldres",
  "Groninga",
  "Holanda Septentrional",
  "Holanda Meridional",
  "Limburgo",
  "Overijssel",
  "Utrecht",
  "Zelanda",

  // Polonia (Voivodatos)
  "Baja Silesia",
  "Cuyavia y Pomerania",
  "Lubusz",
  "Lodz",
  "Lublin",
  "Masovia",
  "Opole",
  "Pequeña Polonia",
  "Pomerania",
  "Silesia",
  "Santa Cruz",
  "Subcarpacia",
  "Varmia y Masuria",
  "Gran Polonia",
  "Pomerania Occidental",

  // Portugal (Distritos y Regiones Autónomas)
  "Aveiro",
  "Beja",
  "Braga",
  "Braganza",
  "Castelo Branco",
  "Coímbra",
  "Évora",
  "Faro",
  "Guarda",
  "Leiria",
  "Lisboa",
  "Oporto",
  "Portalegre",
  "Santarém",
  "Setúbal",
  "Viana do Castelo",
  "Vila Real",
  "Viseu",
  "Azores",
  "Madeira",

  // Reino Unido (Países y Regiones)
  "Inglaterra",
  "Escocia",
  "Gales",
  "Irlanda del Norte",
  "East Midlands",
  "East of England",
  "London",
  "North East",
  "North West",
  "South East",
  "South West",
  "West Midlands",
  "Yorkshire and the Humber",

  // República Checa (Regiones)
  "Bohemia Central",
  "Hradec Králové",
  "Karlovy Vary",
  "Liberec",
  "Moravia-Silesia",
  "Olomouc",
  "Pardubice",
  "Pilsen",
  "Praga",
  "Región de Vysočina",
  "Sur de Bohemia",
  "Sur de Moravia",
  "Ústí nad Labem",
  "Zlín",

  // Rumanía (Condados)
  "Alba",
  "Arad",
  "Argeș",
  "Bacău",
  "Bihor",
  "Bistrița-Năsăud",
  "Botoșani",
  "Brăila",
  "Brașov",
  "Bucarest",
  "Buzău",
  "Călărași",
  "Caraș-Severin",
  "Cluj",
  "Constanța",
  "Covasna",
  "Dâmbovița",
  "Dolj",
  "Galați",
  "Giurgiu",
  "Gorj",
  "Harghita",
  "Hunedoara",
  "Ialomița",
  "Iași",
  "Ilfov",
  "Maramureș",
  "Mehedinți",
  "Mureș",
  "Neamț",
  "Olt",
  "Prahova",
  "Sălaj",
  "Satu Mare",
  "Sibiu",
  "Suceava",
  "Teleorman",
  "Timiș",
  "Tulcea",
  "Vâlcea",
  "Vaslui",
  "Vrancea",

  // Rusia (Regiones, Repúblicas, Krais, Óblasts, y Ciudades Federales)
  "Adiguesia",
  "Altái",
  "Amur",
  "Arjánguelsk",
  "Astracán",
  "Bashkortostán",
  "Belgorod",
  "Bratsk",
  "Buriatia",
  "Chechenia",
  "Cheliábinsk",
  "Chukotka",
  "Chuvashia",
  "Daguestán",
  "Inguria",
  "Irkutsk",
  "Ivánovo",
  "Kabardia-Balkaria",
  "Kaliningrado",
  "Kalmykia",
  "Kaluga",
  "Kamtchatka",
  "Karacháyevo-Cherkesia",
  "Karelia",
  "Kémerovo",
  "Khabarovsk",
  "Khakasia",
  "Khanty-Mansi",
  "Kírov",
  "Komi",
  "Kostromá",
  "Krasnodar",
  "Krasnoyarsk",
  "Kurgán",
  "Kursk",
  "Leningrado",
  "Lípetsk",
  "Magadán",
  "Mari-El",
  "Mordovia",
  "Moscú",
  "Múrmansk",
  "Nenetsia",
  "Nízhni Nóvgorod",
  "Novgorod",
  "Novosibirsk",
  "Omsk",
  "Oremburgo",
  "Oriol",
  "Penza",
  "Perm",
  "Primorie",
  "Pskov",
  "Rostov",
  "Ryazán",
  "Sajalín",
  "Samara",
  "San Petersburgo",
  "Sarátov",
  "Smolensk",
  "Stávropol",
  "Sverdlovsk",
  "Tambov",
  "Tartaristán",
  "Taymyria",
  "Tomsk",
  "Tula",
  "Tuva",
  "Tver",
  "Udmurtia",
  "Ulianovsk",
  "Vladímir",
  "Volgogrado",
  "Vólogda",
  "Vorónezh",
  "Yamalo-Nenets",
  "Yaroslavl",
  "Zabaykalsky",

  // San Marino (Castelli)
  "Acquaviva",
  "Borgo Maggiore",
  "Chiesanuova",
  "Domagnano",
  "Faetano",
  "Fiorentino",
  "Montegiardino",
  "San Marino",
  "Serravalle",

  // Serbia (Distritos y Provincias Autónomas)
  "Borski",
  "Braničevski",
  "Jablanički",
  "Južnobanatski",
  "Južnobački",
  "Kolubarski",
  "Kosovski",
  "Kosovsko-Mitrovački",
  "Kosovsko-Pomoravski",
  "Mačvanski",
  "Moravički",
  "Nišavski",
  "Pčinjski",
  "Pećki",
  "Pirotski",
  "Podunavski",
  "Pomoravski",
  "Prizrenski",
  "Raški",
  "Severnobanatski",
  "Severnobački",
  "Srednjobanatski",
  "Sremski",
  "Šumadijski",
  "Toplički",
  "Zaječarski",
  "Zapadnobački",
  "Zlatiborski",
  "Vojvodina",
  "Kosovo y Metohija",

  // Suecia (Condados)
  "Blekinge",
  "Dalarna",
  "Gotland",
  "Gävleborg",
  "Halland",
  "Jämtland",
  "Jönköping",
  "Kalmar",
  "Kronoberg",
  "Norrbotten",
  "Örebro",
  "Östergötland",
  "Skåne",
  "Estocolmo",
  "Södermanland",
  "Uppsala",
  "Värmland",
  "Västerbotten",
  "Västernorrland",
  "Västmanland",
  "Västra Götaland",

  // Suiza (Cantones)
  "Aargau",
  "Appenzell Rodas Exteriores",
  "Appenzell Rodas Interiores",
  "Basilea-Campiña",
  "Basilea-Ciudad",
  "Berna",
  "Friburgo",
  "Ginebra",
  "Glaris",
  "Grisones",
  "Jura",
  "Lucerna",
  "Neuchâtel",
  "Nidwalden",
  "Obwalden",
  "San Galo",
  "Schaffhausen",
  "Schwyz",
  "Soleura",
  "Ticino",
  "Turgovia",
  "Uri",
  "Vaud",
  "Valais",
  "Zug",
  "Zúrich",

  // Turquía (Provincias)
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Aksaray",
  "Amasya",
  "Ankara",
  "Antalya",
  "Ardahan",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bartın",
  "Batman",
  "Bayburt",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Düzce",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkâri",
  "Hatay",
  "Iğdır",
  "Isparta",
  "Estambul",
  "İzmir",
  "Kahramanmaraş",
  "Karabük",
  "Karaman",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kilis",
  "Kırıkkale",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Mardin",
  "Mersin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Osmaniye",
  "Rize",
  "Sakarya",
  "Samsun",
  "Şanlıurfa",
  "Siirt",
  "Sinop",
  "Şırnak",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Uşak",
  "Van",
  "Yalova",
  "Yozgat",
  "Zonguldak",

  // Ucrania (Óblasts y Repúblicas Autónomas)
  "Cherkasy",
  "Chernihiv",
  "Chernivtsi",
  "Crimea",
  "Dnipropetrovsk",
  "Donetsk",
  "Ivano-Frankivsk",
  "Járkov",
  "Jersón",
  "Jmelnitski",
  "Kiev",
  "Kirovogrado",
  "Lugansk",
  "Leópolis",
  "Mykolaiv",
  "Odessa",
  "Poltava",
  "Rivne",
  "Sumy",
  "Ternópil",
  "Transcarpatia",
  "Vinnytsia",
  "Volinia",
  "Zaporiyia",
  "Zhytomyr",

  // Vaticano
  "Ciudad del Vaticano",
];
const asia = [
  // Afganistán (Provincias)
  "Badakhshan",
  "Badghis",
  "Baghlan",
  "Balkh",
  "Bamyan",
  "Daykundi",
  "Farah",
  "Faryab",
  "Ghazni",
  "Ghor",
  "Helmand",
  "Herat",
  "Jowzjan",
  "Kabul",
  "Kandahar",
  "Kapisa",
  "Khost",
  "Kunar",
  "Kunduz",
  "Laghman",
  "Logar",
  "Nangarhar",
  "Nimroz",
  "Nuristán",
  "Paktia",
  "Paktika",
  "Panjshir",
  "Parwan",
  "Samangan",
  "Sar-e Pol",
  "Takhar",
  "Urozgan",
  "Wardak",
  "Zabul",

  // Arabia Saudita (Regiones)
  "Riad",
  "Meca",
  "Medina",
  "Al-Qasim",
  "Provincia Oriental",
  "Asir",
  "Tabuk",
  "Hail",
  "Provincia Fronteriza Norte",
  "Yazán",
  "Najrán",
  "Al-Baha",
  "Al-Jouf",

  // Armenia (Provincias)
  "Aragatsotn",
  "Ararat",
  "Armavir",
  "Gegharkunik",
  "Kotayk",
  "Lori",
  "Shirak",
  "Syunik",
  "Tavush",
  "Vayots Dzor",
  "Ereván",

  // Azerbaiyán (Regiones, ciudades y repúblicas autónomas)
  "Abşeron",
  "Aran",
  "Ganja-Qazakh",
  "Lankaran",
  "Nakhichevan",
  "Quba-Khachmaz",
  "Shaki-Zaqatala",
  "Yukhari-Karabakh",
  "Baku",
  "Ganja",
  "Sumqayit",

  // Bahréin (Gobernaciones)
  "Capital",
  "Central",
  "Muharraq",
  "Norte",
  "Sur",

  // Bangladés (Divisiones)
  "Barisal",
  "Chittagong",
  "Dhaka",
  "Khulna",
  "Mymensingh",
  "Rajshahi",
  "Rangpur",
  "Sylhet",

  // Birmania/Myanmar (Regiones y Estados)
  "Ayeyarwady",
  "Bago",
  "Magway",
  "Mandalay",
  "Sagaing",
  "Tanintharyi",
  "Yangon",
  "Chin",
  "Kachin",
  "Kayah",
  "Kayin",
  "Mon",
  "Rakhine",
  "Shan",

  // Bután (Dzongkhags)
  "Bumthang",
  "Chukha",
  "Dagana",
  "Gasa",
  "Haa",
  "Lhuntse",
  "Mongar",
  "Paro",
  "Pema Gatshel",
  "Punakha",
  "Samdrup Jongkhar",
  "Samtse",
  "Sarpang",
  "Thimphu",
  "Trashigang",
  "Trashiyangtse",
  "Trongsa",
  "Tsirang",
  "Wangdue Phodrang",
  "Zhemgang",

  // Camboya (Provincias y Municipios)
  "Banteay Meanchey",
  "Battambang",
  "Kampong Cham",
  "Kampong Chhnang",
  "Kampong Speu",
  "Kampong Thom",
  "Kampot",
  "Kandal",
  "Koh Kong",
  "Kratie",
  "Mondulkiri",
  "Oddar Meanchey",
  "Pailin",
  "Phnom Penh",
  "Preah Sihanouk",
  "Preah Vihear",
  "Prey Veng",
  "Pursat",
  "Ratanakiri",
  "Siem Reap",
  "Stung Treng",
  "Svay Rieng",
  "Takeo",
  "Tboung Khmum",

  // China (Provincias, Regiones Autónomas, Municipalidades y Regiones Administrativas Especiales)
  "Anhui",
  "Beijing",
  "Chongqing",
  "Fujian",
  "Gansu",
  "Guangdong",
  "Guangxi",
  "Guizhou",
  "Hainan",
  "Hebei",
  "Heilongjiang",
  "Henan",
  "Hubei",
  "Hunan",
  "Jiangsu",
  "Jiangxi",
  "Jilin",
  "Liaoning",
  "Nei Mongol",
  "Ningxia",
  "Qinghai",
  "Shaanxi",
  "Shandong",
  "Shanghai",
  "Shanxi",
  "Sichuan",
  "Tianjin",
  "Tibet",
  "Xinjiang",
  "Yunnan",
  "Zhejiang",
  "Hong Kong",
  "Macao",

  // Chipre (Distritos)
  "Famagusta",
  "Kyrenia",
  "Larnaca",
  "Limassol",
  "Nicosia",
  "Paphos",

  // Corea del Norte (Provincias y ciudades especiales)
  "Chagang",
  "Hamgyong del Norte",
  "Hamgyong del Sur",
  "Hwanghae del Norte",
  "Hwanghae del Sur",
  "Kangwon",
  "Pyongan del Norte",
  "Pyongan del Sur",
  "Ryanggang",
  "Pyongyang",
  "Rason",

  // Corea del Sur (Provincias y ciudades especiales)
  "Chungcheong del Norte",
  "Chungcheong del Sur",
  "Gangwon",
  "Gyeonggi",
  "Gyeongsang del Norte",
  "Gyeongsang del Sur",
  "Jeolla del Norte",
  "Jeolla del Sur",
  "Jeju",
  "Seúl",
  "Busan",
  "Daegu",
  "Incheon",
  "Gwangju",
  "Daejeon",
  "Ulsan",
  "Sejong",

  // Emiratos Árabes Unidos (Emiratos)
  "Abu Dabi",
  "Ajmán",
  "Dubái",
  "Fuyaira",
  "Ras al-Jaima",
  "Sharjah",
  "Umm al-Qaywayn",

  // Filipinas (Regiones)
  "Región de la Capital Nacional",
  "Región Administrativa en Cordillera",
  "Ilocos",
  "Cagayán Valley",
  "Central Luzon",
  "Calabarzon",
  "Mimaropa",
  "Bicol",
  "Western Visayas",
  "Central Visayas",
  "Eastern Visayas",
  "Zamboanga Peninsula",
  "Northern Mindanao",
  "Davao",
  "Soccsksargen",
  "Caraga",
  "Bangsamoro",

  // Georgia (Regiones Autónomas, Repúblicas y Municipalidades)
  "Adjaria",
  "Abjasia",
  "Guria",
  "Imericia",
  "Kakhetia",
  "Kvemo Kartli",
  "Mtsjeta-Mtianeti",
  "Racha-Lechjumi y Kvemo Svaneti",
  "Samtsje-Yavajeti",
  "Shida Kartli",
  "Tiflis",
  "Samegrelo-Zemo Svaneti",

  // India (Estados y Territorios de la Unión)
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman y Nicobar",
  "Chandigarh",
  "Dadra y Nagar Haveli y Damán y Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
  "Ladakh",
  "Jammu y Cachemira",

  // Indonesia (Provincias)
  "Aceh",
  "Bali",
  "Banten",
  "Bengkulu",
  "Gorontalo",
  "Jakarta",
  "Jambi",
  "Java Occidental",
  "Java Central",
  "Java Oriental",
  "Kalimantan Occidental",
  "Kalimantan Central",
  "Kalimantan Meridional",
  "Kalimantan Oriental",
  "Kalimantan del Norte",
  "Bangka-Belitung",
  "Lampung",
  "Maluku",
  "Maluku Septentrional",
  "Papúa",
  "Papúa Occidental",
  "Riau",
  "Islas Riau",
  "Sulawesi Occidental",
  "Sulawesi Meridional",
  "Sulawesi Central",
  "Sulawesi Sudoriental",
  "Sulawesi Septentrional",
  "Sumatra Occidental",
  "Sumatra Meridional",
  "Sumatra Septentrional",
  "Yogyakarta",

  // Irán (Provincias)
  "Alborz",
  "Ardabil",
  "Azerbaiyán Oriental",
  "Azerbaiyán Occidental",
  "Bushehr",
  "Chahar Mahal y Bajtiarí",
  "Fars",
  "Gilan",
  "Golestán",
  "Hamadan",
  "Hormozgán",
  "Ilam",
  "Isfahán",
  "Kermanshah",
  "Jorasán del Norte",
  "Jorasán del Razaví",
  "Jorasán del Sur",
  "Juzestán",
  "Kerman",
  "Kurdistán",
  "Lorestán",
  "Markazí",
  "Mazandarán",
  "Qazvín",
  "Qom",
  "Semnán",
  "Sistan y Baluchistán",
  "Teherán",
  "Yazd",
  "Zanyán",

  // Irak (Provincias)
  "Al Anbar",
  "Al Muthanna",
  "Al Qadisiyyah",
  "Babil",
  "Bagdad",
  "Basora",
  "Dohuk",
  "Diyala",
  "Erbil",
  "Kerbala",
  "Kirkuk",
  "Mayoralty de Bagdad",
  "Maysan",
  "Nínive",
  "Saladin",
  "Suleimaniya",
  "Thi Qar",
  "Wassit",

  // Israel (Distritos)
  "Distrito Central",
  "Distrito Haifa",
  "Distrito Jerusalén",
  "Distrito Norte",
  "Distrito Meridional",
  "Distrito Tel Aviv",

  // Japón (Prefecturas)
  "Aichi",
  "Akita",
  "Aomori",
  "Chiba",
  "Ehime",
  "Fukui",
  "Fukuoka",
  "Fukushima",
  "Gifu",
  "Gunma",
  "Hiroshima",
  "Hokkaido",
  "Hyogo",
  "Ibaraki",
  "Ishikawa",
  "Iwate",
  "Kagawa",
  "Kagoshima",
  "Kanagawa",
  "Kochi",
  "Kumamoto",
  "Kyoto",
  "Mie",
  "Miyagi",
  "Miyazaki",
  "Nagano",
  "Nagasaki",
  "Nara",
  "Niigata",
  "Oita",
  "Okayama",
  "Okinawa",
  "Osaka",
  "Saga",
  "Saitama",
  "Shiga",
  "Shimane",
  "Shizuoka",
  "Tochigi",
  "Tokio",
  "Tokushima",
  "Tottori",
  "Toyama",
  "Wakayama",
  "Yamagata",
  "Yamaguchi",
  "Yamanashi",

  // Jordania (Gobernaciones)
  "Ajloun",
  "Amán",
  "Aqaba",
  "Balqa",
  "Irbid",
  "Jerash",
  "Karak",
  "Ma'an",
  "Madaba",
  "Mafraq",
  "Tafilah",
  "Zarqa",

  // Kazajistán (Regiones y ciudades autónomas)
  "Almaty",
  "Akmola",
  "Aktobe",
  "Almaty",
  "Atyrau",
  "Balkhash",
  "East Kazakhstan",
  "Jambyl",
  "Karaganda",
  "Kostanay",
  "Kyzylorda",
  "Mangystau",
  "North Kazakhstan",
  "Pavlodar",
  "South Kazakhstan",
  "West Kazakhstan",
  "Astana",
  "Shymkent",

  // Kuwait (Gobernaciones)
  "Al Ahmadi",
  "Al Farwaniyah",
  "Al Asimah",
  "Al Jahra",
  "Mubarak Al-Kabeer",
  "Hawalli",

  // Kirguistán (Provincias y ciudades autónomas)
  "Batken",
  "Chuy",
  "Jalal-Abad",
  "Naryn",
  "Osh",
  "Talas",
  "Ysyk-Kol",
  "Bishkek",
  "Osh",

  // Laos (Provincias y Prefecturas)
  "Attapeu",
  "Bokeo",
  "Bolikhamxai",
  "Champasak",
  "Houaphanh",
  "Khammouane",
  "Luang Namtha",
  "Luang Prabang",
  "Oudomxay",
  "Phongsaly",
  "Salavan",
  "Savannakhet",
  "Sekong",
  "Vientiane",
  "Vientiane Prefecture",
  "Xaignabouli",
  "Xekong",
  "Xieng Khouang",

  // Líbano (Gobernaciones)
  "Akkar",
  "Baalbek-Hermel",
  "Beirut",
  "Beqaa",
  "Líbano Norte",
  "Líbano Sur",
  "Monte Líbano",
  "Nabatieh",

  // Malasia (Estados y Territorios Federales)
  "Johor",
  "Kedah",
  "Kelantan",
  "Malacca",
  "Negeri Sembilan",
  "Pahang",
  "Penang",
  "Perak",
  "Perlis",
  "Sabah",
  "Sarawak",
  "Selangor",
  "Terengganu",
  "Kuala Lumpur",
  "Labuan",
  "Putrajaya",

  // Maldivas (Atolones)
  "Alif Alif",
  "Alif Dhaal",
  "Baa",
  "Dhaal",
  "Faafu",
  "Gaafu Alif",
  "Gaafu Dhaal",
  "Gnaviyani",
  "Haa Alif",
  "Haa Dhaalu",
  "Kaafu",
  "Laamu",
  "Lhaviyani",
  "Meemu",
  "Noonu",
  "Raa",
  "Seenu",
  "Shaviyani",
  "Thaa",
  "Vaavu",

  // Mongolia (Provincias y ciudades autónomas)
  "Arkhangai",
  "Bayankhongor",
  "Bayan-Olgii",
  "Bulgan",
  "Darkhan-Uul",
  "Dornod",
  "Dornogovi",
  "Dundgovi",
  "Govi-Altai",
  "Govisumber",
  "Khentii",
  "Khovd",
  "Khovsgol",
  "Orkhon",
  "Ovorkhangai",
  "Selenge",
  "Sukhbaatar",
  "Tov",
  "Uvs",
  "Zavkhan",
  "Ulaanbaatar",

  // Nepal (Provincias)
  "Bagmati",
  "Gandaki",
  "Karnali",
  "Lumbini",
  "Madhesh",
  "Sudurpashchim",
  "Provincia No. 1",

  // Omán (Gobernaciones)
  "Ad Dakhiliyah",
  "Al Batinah North",
  "Al Batinah South",
  "Al Buraimi",
  "Al Dhahirah",
  "Al Wusta",
  "Dhofar",
  "Musandam",
  "Mascate",
  "Ash Sharqiyah North",
  "Ash Sharqiyah South",

  // Pakistán (Provincias, Territorios y Áreas)
  "Baluchistán",
  "Gilgit-Baltistán",
  "Islamabad",
  "Khyber Pakhtunkhwa",
  "Punyab",
  "Sindh",
  "Azad Cachemira",
  "Áreas Tribales Administradas Federalmente",

  // Palestina (Gobernaciones)
  "Cisjordania",
  "Gaza",
  "Hebrón",
  "Jenin",
  "Jericó y el Valle del Jordán",
  "Jerusalén",
  "Khan Yunis",
  "Nablus",
  "Qalqilya",
  "Rafah",
  "Ramallah y al-Bireh",
  "Salfit",
  "Tubas",
  "Tulkarem",

  // Qatar (Municipios)
  "Ad Dawhah",
  "Al Daayen",
  "Al Khor",
  "Al Rayyan",
  "Al Shamal",
  "Al Wakrah",
  "Umm Salal",

  // Siria (Gobernaciones)
  "Al-Hasakah",
  "Al-Raqqah",
  "Aleppo",
  "As-Suwayda",
  "Damasco",
  "Daraa",
  "Deir ez-Zor",
  "Hama",
  "Homs",
  "Idlib",
  "Latakia",
  "Quneitra",
  "Rif Dimashq",
  "Tartus",

  // Sri Lanka (Provincias)
  "Central",
  "Este",
  "Noroeste",
  "Norte",
  "Noreste",
  "Sabaragamuwa",
  "Sur",
  "Uva",
  "Oeste",

  // Tailandia (Provincias)
  "Amnat Charoen",
  "Ang Thong",
  "Ayutthaya",
  "Bangkok",
  "Buriram",
  "Chachoengsao",
  "Chai Nat",
  "Chaiyaphum",
  "Chanthaburi",
  "Chiang Mai",
  "Chiang Rai",
  "Chonburi",
  "Chumphon",
  "Kalasin",
  "Kamphaeng Phet",
  "Kanchanaburi",
  "Khon Kaen",
  "Krabi",
  "Lampang",
  "Lamphun",
  "Loei",
  "Lopburi",
  "Mae Hong Son",
  "Maha Sarakham",
  "Mukdahan",
  "Nakhon Nayok",
  "Nakhon Pathom",
  "Nakhon Phanom",
  "Nakhon Ratchasima",
  "Nakhon Sawan",
  "Nakhon Si Thammarat",
  "Nan",
  "Narathiwat",
  "Nong Bua Lamphu",
  "Nong Khai",
  "Nonthaburi",
  "Pathum Thani",
  "Pattani",
  "Phang Nga",
  "Phatthalung",
  "Phayao",
  "Phetchabun",
  "Phetchaburi",
  "Phichit",
  "Phitsanulok",
  "Phrae",
  "Phuket",
  "Prachinburi",
  "Prachuap Khiri Khan",
  "Ranong",
  "Ratchaburi",
  "Rayong",
  "Roi Et",
  "Sa Kaeo",
  "Sakon Nakhon",
  "Samut Prakan",
  "Samut Sakhon",
  "Samut Songkhram",
  "Saraburi",
  "Satun",
  "Sing Buri",
  "Si Sa Ket",
  "Songkhla",
  "Sukhothai",
  "Suphan Buri",
  "Surat Thani",
  "Surin",
  "Tak",
  "Trang",
  "Trat",
  "Ubon Ratchathani",
  "Udon Thani",
  "Uthai Thani",
  "Uttaradit",
  "Yala",
  "Yasothon",

  // Tayikistán (Provincias y regiones autónomas)
  "Badajshán",
  "Gorno-Badakhshan",
  "Hatlon",
  "Sughd",
  "Distrito de Subordinación Republicana",
  "Dushanbe",

  // Timor Oriental (Municipios)
  "Aileu",
  "Ainaro",
  "Baucau",
  "Bobonaro",
  "Cova Lima",
  "Dili",
  "Ermera",
  "Lautem",
  "Liquiçá",
  "Manatuto",
  "Manufahi",
  "Oecusse",
  "Viqueque",

  // Turkmenistán (Regiones)
  "Ahal",
  "Balkan",
  "Daşoguz",
  "Lebap",
  "Mary",
  "Ashgabat",

  // Turquía (Provincias)
  "Adana",
  "Adiyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Aksaray",
  "Amasya",
  "Ankara",
  "Antalya",
  "Ardahan",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bartın",
  "Batman",
  "Bayburt",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Düzce",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkâri",
  "Hatay",
  "Iğdır",
  "Isparta",
  "İstanbul",
  "İzmir",
  "Kahramanmaraş",
  "Karabük",
  "Karaman",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kilis",
  "Kırıkkale",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Mardin",
  "Mersin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Osmaniye",
  "Rize",
  "Sakarya",
  "Samsun",
  "Şanlıurfa",
  "Siirt",
  "Sinop",
  "Şırnak",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Uşak",
  "Van",
  "Yalova",
  "Yozgat",
  "Zonguldak",

  // Uzbekistán (Regiones)
  "Andiján",
  "Bujará",
  "Ferganá",
  "Jizzaj",
  "Jorezm",
  "Namangán",
  "Navai",
  "Samarkanda",
  "Sirdaryo",
  "Surjandarín",
  "Tashkent",
  "Qashqadaryo",
  "Karakalpakstán",

  // Vietnam (Municipios y provincias)
  "An Giang",
  "Ba Ria-Vung Tau",
  "Bac Giang",
  "Bac Kan",
  "Bac Lieu",
  "Bac Ninh",
  "Ben Tre",
  "Binh Dinh",
  "Binh Duong",
  "Binh Phuoc",
  "Binh Thuan",
  "Ca Mau",
  "Can Tho",
  "Cao Bang",
  "Da Nang",
  "Dak Lak",
  "Dak Nong",
  "Dien Bien",
  "Dong Nai",
  "Dong Thap",
  "Gia Lai",
  "Ha Giang",
  "Ha Nam",
  "Ha Noi",
  "Ha Tinh",
  "Hai Duong",
  "Hai Phong",
  "Hau Giang",
  "Hoa Binh",
  "Ho Chi Minh City",
  "Hung Yen",
  "Khanh Hoa",
  "Kien Giang",
  "Kon Tum",
  "Lai Chau",
  "Lam Dong",
  "Lang Son",
  "Lao Cai",
  "Long An",
  "Nam Dinh",
  "Nghe An",
  "Ninh Binh",
  "Ninh Thuan",
  "Phu Tho",
  "Phu Yen",
  "Quang Binh",
  "Quang Nam",
  "Quang Ngai",
  "Quang Ninh",
  "Quang Tri",
  "Soc Trang",
  "Son La",
  "Tay Ninh",
  "Thai Binh",
  "Thai Nguyen",
  "Thanh Hoa",
  "Thua Thien-Hue",
  "Tien Giang",
  "Tra Vinh",
  "Tuyen Quang",
  "Vinh Long",
  "Vinh Phuc",
  "Yen Bai",

  // Yemen (Gobernaciones)
  "Abyan",
  "Adén",
  "Ad Dali",
  "Amran",
  "Dhamar",
  "Hadramaut",
  "Hajjah",
  "Ibb",
  "Lahej",
  "Mahra",
  "Ma'rib",
  "Raymah",
  "Sa'dah",
  "Sana'a",
  "Shabwah",
  "Socotra",
  "Taiz",
];
const oceania = [
  // Australia (Estados y territorios)
  "New South Wales",
  "Queensland",
  "South Australia",
  "Tasmania",
  "Victoria",
  "Western Australia",
  "Australian Capital Territory",
  "Northern Territory",

  // Fiji (Divisiones y Rotuma)
  "Central",
  "Eastern",
  "Northern",
  "Western",
  "Rotuma",

  // Islas Marshall (Atolones y islas)
  "Ailinginae",
  "Ailinglaplap",
  "Ailuk",
  "Arno",
  "Aur",
  "Bikar",
  "Bikini",
  "Bokak",
  "Ebon",
  "Enewetak",
  "Erikub",
  "Jabat",
  "Jaluit",
  "Jemo",
  "Kili",
  "Kwajalein",
  "Lae",
  "Lib",
  "Likiep",
  "Majuro",
  "Maloelap",
  "Mejit",
  "Mili",
  "Namdrik",
  "Namu",
  "Rongelap",
  "Rongrik",
  "Toke",
  "Ujae",
  "Ujelang",
  "Utirik",
  "Wotho",
  "Wotje",

  // Kiribati (Islas y grupos de islas)
  "Banaba",
  "Islas de la Línea",
  "Islas Gilbert",
  "Islas Fénix",

  // Micronesia (Estados)
  "Chuuk",
  "Kosrae",
  "Pohnpei",
  "Yap",

  // Nauru (Distritos)
  "Aiwo",
  "Anabar",
  "Anetan",
  "Anibare",
  "Baiti",
  "Boe",
  "Buada",
  "Denigomodu",
  "Ewa",
  "Ijuw",
  "Meneng",
  "Nibok",
  "Uaboe",
  "Yaren",

  // Nueva Zelanda (Regiones y territorios)
  "Auckland",
  "Bay of Plenty",
  "Canterbury",
  "Gisborne",
  "Hawke's Bay",
  "Manawatu-Wanganui",
  "Marlborough",
  "Nelson",
  "Northland",
  "Otago",
  "Southland",
  "Taranaki",
  "Tasman",
  "Waikato",
  "Wellington",
  "West Coast",
  "Chatham Islands Territory",

  // Palau (Estados)
  "Aimeliik",
  "Airai",
  "Angaur",
  "Hatohobei",
  "Kayangel",
  "Koror",
  "Melekeok",
  "Ngaraard",
  "Ngarchelong",
  "Ngardmau",
  "Ngatpang",
  "Ngchesar",
  "Ngeremlengui",
  "Ngiwal",
  "Peleliu",
  "Sonsorol",

  // Papua Nueva Guinea (Provincias y regiones autónomas)
  "Bougainville",
  "Central",
  "Chimbu",
  "Eastern Highlands",
  "East New Britain",
  "East Sepik",
  "Enga",
  "Gulf",
  "Hela",
  "Jiwaka",
  "Madang",
  "Manus",
  "Milne Bay",
  "Morobe",
  "New Ireland",
  "Northern",
  "Southern Highlands",
  "West New Britain",
  "West Sepik",
  "Western",
  "Western Highlands",

  // Samoa (Distritos)
  "A'ana",
  "Aiga-i-le-Tai",
  "Atua",
  "Fa'asaleleaga",
  "Gaga'emauga",
  "Gaga'ifomauga",
  "Palauli",
  "Satupa'itea",
  "Tuamasaga",
  "Va'a-o-Fonoti",
  "Vaisigano",

  // Islas Salomón (Provincias)
  "Central",
  "Choiseul",
  "Guadalcanal",
  "Honiara",
  "Isabel",
  "Makira-Ulawa",
  "Malaita",
  "Rennell and Bellona",
  "Temotu",
  "Western",

  // Tonga (Divisiones)
  "Tongatapu",
  "Ha'apai",
  "Vava'u",
  "Niuas",
  "Eua",

  // Tuvalu (Islas)
  "Funafuti",
  "Nanumanga",
  "Nanumea",
  "Niutao",
  "Nui",
  "Nukufetau",
  "Nukulaelae",
  "Vaitupu",

  // Vanuatu (Provincias)
  "Malampa",
  "Penama",
  "Sanma",
  "Shefa",
  "Tafea",
  "Torba",
];
const gbaLocalidades = [
  // Almirante Brown
  "Adrogué",
  "Burzaco",
  "Claypole",
  "Glew",
  "Longchamps",
  "Malvinas Argentinas",
  "Rafael Calzada",
  "San José",
  "Temperley",
  "Villa Albertina",
  "Villa La Nación",
  "Villa Dorrego",

  // Avellaneda
  "Avellaneda",
  "Gerli",
  "Dock Sud",
  "Piñeyro",
  "Sarandí",
  "Avellaneda",
  " Wilde",
  "Villa Domínico",

  // Berazategui
  "Berazategui",
  "El Pato",
  "Hudson",
  "Ranelagh",
  "Savannah",
  "Villa España",
  "Villa Mitre",
  "Plátanos",

  // Bonaerense
  "Bonaerense",
  "Lomas de Zamora",
  "Guernica",

  // Cañuelas
  "Cañuelas",
  "Lobos",
  "Ranchos",
  "San Esteban",

  // Esteban Echeverría
  "El Jagüel",
  "Monte Grande",
  "Luis Guillón",
  "Esteban Echeverría",

  // Ezeiza
  "Ezeiza",
  "El Aeropuerto",
  "La Unión",

  // Florencio Varela
  "Bosques",
  "Florencio Varela",
  "La Capilla",
  "Villa Varela",

  // Hurlingham
  "Hurlingham",
  "Villa Tesei",
  "San Alberto",
  "San Juan",
  "William Morris",

  // Ituzaingó
  "Ituzaingó",
  "Villa Udaondo",
  "El Palomar",
  "Castelar",

  // José C. Paz
  "José C. Paz",
  "La Paz",
  "Villa de Mayo",
  "Malabrigo",

  // La Matanza
  "San Justo",
  "Rafael Castillo",
  "La Tablada",
  "Tapiales",
  "Villa Luzuriaga",
  "Gregorio de Laferrere",
  "Lomas del Mirador",
  "Isidro Casanova",
  "Villa Celina",
  "Virrey del Pino",
  "Ramos Mejía",

  // Lanús
  "Lanús",
  "Remedios de Escalada",
  "Valentín Alsina",
  "Lanús Este",
  "Lanús Oeste",

  // Lomas de Zamora
  "Lomas de Zamora",
  "Banfield",
  "Temperley",
  "Remedios de Escalada",
  "Adrogué",
  "Longchamps",
  "Ingeniero Budge",
  "Villa Fiorito",

  // Malvinas Argentinas
  "Malvinas Argentinas",
  "Grand Bourg",
  "Villa de Mayo",
  "Los Polvorines",
  "Pablo Nogués",
  "Pablo Nogués",

  // Merlo
  "Merlo",
  "San Antonio de Padua",
  "Libertad",
  "Mariano Acosta",
  "Parque San Martín",
  "Villa Eva Perón",

  // Morón
  "Morón",
  "Castelar",
  "El Palomar",
  "Haedo",
  "Ituzaingó",
  "Villa Sarmiento",

  // Pilar
  "Pilar",
  "Derqui",
  "Manuel Alberti",
  "Villa Rosa",
  "Laguna del Sol",
  "La Lonja",
  "Fátima",

  // Quilmes
  "Quilmes",
  "Bernal",
  "Ezpeleta",
  "San Francisco Solano",
  "Quilmes Oeste",
  "Quilmes Este",

  // San Fernando
  "San Fernando",
  "Victoria",
  "Virreyes",
  "El Barrio de la Isla",

  // San Isidro
  "San Isidro",
  "Boulogne",
  "La Horqueta",
  "Acassuso",
  "Martínez",
  "Beccar",

  // San Martín
  "San Martín",
  "Villa Maipú",
  "José León Suárez",
  "San Andrés",
  "Villa Ballester",

  // San Miguel
  "San Miguel",
  "Los Polvorines",
  "Malvinas Argentinas",
  "Bella Vista",
  "Muñiz",

  // Tigre
  "Tigre",
  "General Pacheco",
  "Benavídez",
  "El Talar",
  "Don Torcuato",
  "Nordelta",

  // Tres de Febrero
  "Tres de Febrero",
  "Caseros",
  "Ciudadela",
  "El Palomar",
  "San Martín",
  "Villa Raffo",

  // Vicente López
  "Vicente López",
  "Olivos",
  "La Lucila",
  "Munro",
  "Carapachay",
];
const localidadesFueraGBA = [
  // Partido de La Plata
  "La Plata",
  "Tolosa",
  "City Bell",
  "Villa Elisa",
  "Gonnet",
  "Los Hornos",
  "San Carlos",
  "Ringuelet",
  "Villa Elvira",
  "Altos de San Lorenzo",
  "Abasto",
  "Arana",
  "El Peligro",
  "Etcheverry",
  "Lisandro Olmos",
  "Melchor Romero",

  // Partido de Bahía Blanca
  "Bahía Blanca",
  "General Daniel Cerri",
  "Ingeniero White",
  "Cabildo",
  "Villa Harding Green",
  "Villa Rosal",
  "Villa Bordeu",
  "Villa Espora",

  // Partido de Mar del Plata (General Pueyrredón)
  "Mar del Plata",
  "Batán",
  "Chapadmalal",
  "Sierra de los Padres",
  "Playa Chapadmalal",
  "Estación Chapadmalal",
  "Camet",
  "Estación Camet",
  "Barrio Félix U. Camet",

  // Partido de Tandil
  "Tandil",
  "María Ignacia (Vela)",
  "Gardey",
  "Azucena",
  "Desvío Aguirre",
  "Irazusta",
  "La Hilda",
  "De la Canal",
  "Las Peñas",
  "Sierra Alta",

  // Partido de Junín
  "Junín",
  "Agustín Roca",
  "Saforcada",
  "Morse",
  "Agustina",
  "Balneario Laguna de Gómez",
  "Fortín Tiburcio",
  "La Agraria",
  "Laplacette",
  "Los Apestados",

  // Partido de Pergamino
  "Pergamino",
  "Manuel Ocampo",
  "Mariano Benítez",
  "El Socorro",
  "Fontezuela",
  "Rancagua",
  "Pinzón",
  "Acevedo",
  "J. A. de la Peña",
  "Urquiza",

  // Partido de San Nicolás
  "San Nicolás de los Arroyos",
  "La Emilia",
  "Conesa",
  "General Rojo",
  "Villa Esperanza",
  "Erézcano",
  "Villa Campi",
  "Villa Hermosa",
  "Villa Riccio",

  // Partido de Necochea
  "Necochea",
  "Quequén",
  "Ramón Santamarina",
  "La Dulce",
  "Claraz",
  "Juan N. Fernández",
  "Energía",

  // Partido de Olavarría
  "Olavarría",
  "Sierra Chica",
  "Loma Negra",
  "Sierras Bayas",
  "Hinojo",
  "Colonia San Miguel",
  "Colonia Hinojo",
  "Santa Luisa",
  "Mapis",
  "Recalde",
  "Espigas",
  "Blanca Grande",

  // Partido de Chivilcoy
  "Chivilcoy",
  "Moquehuá",
  "Gorostiaga",
  "Emilio Ayarza",
  "Ramón Biaus",
  "La Rica",
  "Benítez",
  "Indacochea",
  "San Sebastián",
  "Ayce",
  "Pueblo Nuevo",

  // Partido de Trenque Lauquen
  "Trenque Lauquen",
  "Beruti",
  "30 de Agosto",
  "Girodías",
  "La Carreta",
  "Salazar",
  "Treinta de Agosto",
  "Colonia Martín Fierro",

  // Partido de General Alvarado
  "Miramar",
  "Comandante Nicanor Otamendi",
  "Mechongué",
  "Mar del Sud",
  "Centinela del Mar",
  "Estación Chapadmalal",

  // Partido de Azul
  "Azul",
  "Cacharí",
  "Chillar",
  "16 de Julio",
  "Pablo Acosta",
  "Ariel",
  "El Mirador",
  "Rauch Viejo",

  // Partido de Chacabuco
  "Chacabuco",
  "Rawson",
  "O'Higgins",
  "Castilla",
  "Cucha Cucha",

  // Partido de Dolores
  "Dolores",
  "Paraje Sevigné",
  "Paraje Parravicini",
  "Salomón",
  "Altamirano",
  "Florencio Sánchez",
  "La Postrera",

  // Partido de Balcarce
  "Balcarce",
  "San Agustín",
  "Los Pinos",
  "Napaleofú",
  "Paraje San Isidro",
  "Fulton",
  "Villa Laguna Brava",

  // Partido de General Villegas
  "General Villegas",
  "Banderaló",
  "Cañada Seca",
  "Cerro Águila",
  "Emilio V. Bunge",
  "Santa Regina",
  "Piedritas",
  "Santa Eleodora",
  "Villa Sauze",

  // Partido de Luján
  "Luján",
  "Carlos Keen",
  "Jáuregui",
  "Olivera",
  "Open Door",
  "Torres",
  "Villa Flandria",
  "Villa Ruiz",

  // Partido de Campana
  "Campana",
  "Villanueva",
  "Alto Los Cardales",
  "Paraje El Tatú",
  "Paraje Las Campanas",
  "Lago Los Molinos",

  // Partido de General Rodríguez
  "General Rodríguez",
  "Marcos Paz",
  "Las Malvinas",
  "Parque Irigoyen",
  "Altos de la Cruz",
  "San Enrique",
  "El Casco",
  "Las Lomas",

  // Partido de Pilar
  "Del Viso",
  "Fátima",
  "Manuel Alberti",
  "Manzanares",
  "Villa Rosa",
  "Villa Astolfi",
  "Pilar",
  "La Lonja",

  // Partido de Mercedes
  "Mercedes",
  "Agote",
  "Altamira",
  "Gowland",
  "Goldney",
  "Tomás Jofré",
  "Cuartel VI",
  "San Jacinto",

  // Partido de Lobos
  "Lobos",
  "Salvador María",
  "Elvira",
  "Villa Loguercio",
  "Empalme Lobos",
  "Jardín del Sur",

  // Partido de San Pedro
  "San Pedro",
  "Santa Lucía",
  "Río Tala",
  "Gobernador Castro",
  "Vuelta de Obligado",
  "Ingeniero Moneta",
  "Paraje La Buena Moza",

  // Partido de Tres Arroyos
  "Tres Arroyos",
  "Orense",
  "Claromecó",
  "Reta",
  "San Mayol",
  "Lin Calel",
  "Cascallares",
  "Barrow",

  // Partido de Pergamino
  "Pergamino",
  "Alfonzo",
  "Rancagua",
  "Manuel Ocampo",
  "Acevedo",
  "Pueblo Alfonzo",
  "J. A. de la Peña",

  // Partido de Tigre
  "Tigre",
  "General Pacheco",
  "Benavídez",
  "El Talar",
  "Rincón de Milberg",
  "Nordelta",
  "Dique Luján",

  // Otros municipios y localidades
  "Salto",
  "Capilla del Señor",
  "San Vicente",
  "Chascomús",
  "Rauch",
  "Las Flores",
  "Lobería",
  "Coronel Suárez",
  "San Andrés de Giles",
  "General Las Heras",
  "Colón",
  "Rojas",
  "Carlos Casares",
  "Pehuajó",
  "Nueve de Julio",
  "9 de Julio",
  "Necochea",
  "Benito Juárez",
  "La Madrid",
  "Puan",
  "Salliqueló",
  "Saavedra",
  "Guaminí",
  "Carmen de Areco",
  "Vedia",
  "Lincoln",
  "Chascomús",
  "Ayacucho",
  "Brandsen",
  "Monte Hermoso",
  "Marcos Paz",
  "Coronel Pringles",
  "Lezama",
  "San Cayetano",
  "Punta Indio",
];
const barriosCABA = [
  "Agronomía",
  "Almagro",
  "Balvanera",
  "Barracas",
  "Belgrano",
  "Boca",
  "Boedo",
  "Caballito",
  "Chacarita",
  "Coghlan",
  "Colegiales",
  "Constitución",
  "Flores",
  "Floresta",
  "La Paternal",
  "Liniers",
  "Mataderos",
  "Monte Castro",
  "Monserrat",
  "Nueva Pompeya",
  "Núñez",
  "Palermo",
  "Parque Avellaneda",
  "Parque Chacabuco",
  "Parque Chas",
  "Parque Patricios",
  "Puerto Madero",
  "Recoleta",
  "Retiro",
  "Saavedra",
  "San Cristóbal",
  "San Nicolás",
  "San Telmo",
  "Versalles",
  "Villa Crespo",
  "Villa del Parque",
  "Villa Devoto",
  "Villa General Mitre",
  "Villa Lugano",
  "Villa Luro",
  "Villa Ortúzar",
  "Villa Pueyrredón",
  "Villa Real",
  "Villa Riachuelo",
  "Villa Santa Rita",
  "Villa Soldati",
  "Villa Urquiza",
];

const allDivisiones = [
  ...americaDelSur,
  ...americaCentral,
  ...americaDelNorte,
  ...europa,
  ...asia,
  ...oceania,
  ...gbaLocalidades,
  ...localidadesFueraGBA,
  ...barriosCABA,
];

export default allDivisiones;
